[features]
seeds = false
[programs.localnet]
solblog = "FCtA4LKBeUFbG7FawMcsy3x7uXVdCHVj8wsGkNsrTA59"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/solana/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
